スタイル:
  sketch: スケッチ
  watercolor: 水彩
  oil painting: 油彩
  thick outline: 厚い輪郭
  black outline: 黒い輪郭
  photorealistic: 写実的
  illustration: イラスト

感情・表情:
  smile: 笑顔
  crying face: 泣き顔
  blush: 頬染め
  sad: 悲しみ
  angry: 怒り

髪型:
  long hair: ロングヘア
  short hair: ショートヘア
  medium hair: セミロング
  twintails: ツインテール
  ponytail: ポニーテール
  side ponytail: サイドテール
  two side up: ツーサイドアップ
  bob cut: ボブ

  髪色:
    black hair: 黒髪
    brown hair: 茶髪
    blonde hair: 金髪
    pink hair: ピンク髪
    red hair: 赤髪
    green hair: 緑髪
    blue hair: 青髪
    aqua hair: 青緑髪（アクア）
    grey hair: 銀髪
    purple hair: 紫髪
    white hair: 白髮

目:
 目の色:
    black eyes: 黒目
    brown eyes: 茶目
    yellow eyes: 金眼
    pink eyes: ピンク目
    blue eyes: 碧眼（青）
    heterochromia: オッドアイ

服装:
  dress: ドレス・ワンピース
  kimono, japanese clothes: 着物
  
  職業服:
    school uniform: 制服
    nurse: ナース
    playboy bunny: バニーガール
    cheerleader: チアガール

  水着:
    swimsuit: 水着(スク水寄り)
    bikini: ビキニ

  アクセサリ:
    hat: 帽子
    straw hat: 麦わら帽子
    mask: マスク
    gloves: 手袋
    ribbon: リボン
    hair bow: ヘアリボン
    circlet: サークレット

  オプション:
    open clothes: はだけている状態
    zettai ryouiki: 絶対領域

特徴:
  セット:
    cat ears,cat tails: 猫耳+猫しっぽ
    fake rabbit ears, fake rabbit tail: うさ耳+しっぽ（飾り）

  顔:
    mole: ほくろ
  
  手:
    nail polish: マニキュア

ポーズ:
  standing: 立ち姿
  lying: 寝そべり
  on back: 仰向け
  on stomach: うつ伏せ
  running: 走っている姿
  sitting: 座っている

オプション:
  水分:
    dripping: 股の滴り
    sweat: 汗
    wet: 水滴
    steam: 蒸れ

  光:
    cinematic lighting: 映画的ライティング
    lens flare: レンズフレア
    light_leaks: 木漏れ日

視点・画角:
  looking at viewer: カメラ目線
  facing viewer: カメラ目線（目閉じ）
  closed eyes: カメラ目線（目開け）
  selfie: 自撮り
  selfie embarrassment mirror: 鏡自撮り
  from side: 横から
  from above: 上から
  from behind: 後ろから
  from below: 下から
  fisheye: 魚眼
  panorama: パノラマ
  ceiling: 見上げる

場所:
  outdoors: 屋外
  indoors: 屋内
  beachside: ビーチサイド
  beach: ビーチ
  shore: 海岸
  library: 図書館
  rooftop: 屋上
  bathroom: 風呂
  onsen: 温泉
  bathtub: バスタブ
  shower room: シャワー



